# Generated by Django 3.0.4 on 2020-06-06 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullTextAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'FullTextAnnotation',
            },
        ),
        migrations.CreateModel(
            name='LandmarkAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'LandmarkAnnotations',
            },
        ),
        migrations.CreateModel(
            name='uploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'uploadFile',
            },
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('upassword', models.CharField(max_length=50)),
                ('utype', models.CharField(default='user', max_length=10)),
                ('uactivated', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UploadFileAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=1000)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'UploadFileAnnotations',
            },
        ),
        migrations.CreateModel(
            name='TextAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=5)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'TextAnnotations',
            },
        ),
        migrations.CreateModel(
            name='SafeSearchAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.CharField(max_length=100)),
                ('medical', models.CharField(max_length=100)),
                ('racy', models.CharField(max_length=100)),
                ('spoof', models.CharField(max_length=100)),
                ('violence', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'SafeSearchAnnotation',
            },
        ),
        migrations.CreateModel(
            name='LogoAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'LogoAnnotations',
            },
        ),
        migrations.CreateModel(
            name='LocationAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('landmarkid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.LandmarkAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'LocationAnnotations',
            },
        ),
        migrations.CreateModel(
            name='LocalizedObjectAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'LocalizedObjectAnnotations',
            },
        ),
        migrations.CreateModel(
            name='LanguageAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('languageCode', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('fulltextid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.FullTextAnnotation')),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'LanguageAnnotations',
            },
        ),
        migrations.AddField(
            model_name='landmarkannotations',
            name='imageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations'),
        ),
        migrations.AddField(
            model_name='landmarkannotations',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom'),
        ),
        migrations.CreateModel(
            name='LabelAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'LabelAnnotations',
            },
        ),
        migrations.CreateModel(
            name='ImagePropertiesAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('red', models.CharField(max_length=3)),
                ('green', models.CharField(max_length=3)),
                ('blue', models.CharField(max_length=3)),
                ('pixelFraction', models.CharField(max_length=20)),
                ('alpha', models.CharField(max_length=20)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'ImagePropertiesAnnotation',
            },
        ),
        migrations.AddField(
            model_name='fulltextannotation',
            name='imageid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations'),
        ),
        migrations.AddField(
            model_name='fulltextannotation',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom'),
        ),
        migrations.CreateModel(
            name='FaceAnnotations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anger', models.CharField(max_length=100)),
                ('blurred', models.CharField(max_length=100)),
                ('headwear', models.CharField(max_length=100)),
                ('joy', models.CharField(max_length=100)),
                ('sorrow', models.CharField(max_length=100)),
                ('surprise', models.CharField(max_length=100)),
                ('underExposed', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'FaceAnnotations',
            },
        ),
    ]
