# Generated by Django 3.0.4 on 2020-06-03 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.IntegerField(auto_created=True)),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('upassword', models.CharField(max_length=50)),
                ('utype', models.CharField(default='user', max_length=10)),
                ('uactivated', models.BooleanField(default=False)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UploadFileAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='')),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UserCustom')),
            ],
            options={
                'db_table': 'UploadFileAnnotations',
            },
        ),
        migrations.CreateModel(
            name='TextAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=5)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'TextAnnotations',
            },
        ),
        migrations.CreateModel(
            name='SafeSearchAnnotation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('adult', models.CharField(max_length=100)),
                ('medical', models.CharField(max_length=100)),
                ('racy', models.CharField(max_length=100)),
                ('spoof', models.CharField(max_length=100)),
                ('violence', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'SafeSearchAnnotation',
            },
        ),
        migrations.CreateModel(
            name='LocalizedObjectAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'LocalizedObjectAnnotations',
            },
        ),
        migrations.CreateModel(
            name='LandmarkAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'LandmarkAnnotations',
            },
        ),
        migrations.CreateModel(
            name='LabelAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'LabelAnnotations',
            },
        ),
        migrations.CreateModel(
            name='ImagePropertiesAnnotation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'ImagePropertiesAnnotation',
            },
        ),
        migrations.CreateModel(
            name='FullTextAnnotation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'FullTextAnnotation',
            },
        ),
        migrations.CreateModel(
            name='FaceAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('anger', models.CharField(max_length=100)),
                ('blurred', models.CharField(max_length=100)),
                ('headwear', models.CharField(max_length=100)),
                ('joy', models.CharField(max_length=100)),
                ('sorrow', models.CharField(max_length=100)),
                ('surprise', models.CharField(max_length=100)),
                ('underExposed', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'FaceAnnotations',
            },
        ),
    ]
