# Generated by Django 3.0.4 on 2020-03-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
