# Generated by Django 3.0.4 on 2020-06-03 22:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logoAnnotations',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrandAnalysisApp.UploadFileAnnotations')),
            ],
            options={
                'db_table': 'logoAnnotations',
            },
        ),
    ]
