# Generated by Django 3.0.4 on 2020-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepropertiesannotation',
            name='blue',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='imagepropertiesannotation',
            name='green',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='imagepropertiesannotation',
            name='red',
            field=models.CharField(max_length=6),
        ),
    ]
