# Generated by Django 3.0.4 on 2020-06-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textannotations',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
