# Generated by Django 3.0.4 on 2020-06-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0002_logoannotations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logoannotations',
            table='LogoAnnotations',
        ),
    ]
