# Generated by Django 3.0.4 on 2020-06-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0002_auto_20200608_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltextannotation',
            name='text',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='labelannotations',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='landmarkannotations',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='logoannotations',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reporttable',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
