# Generated by Django 3.0.4 on 2020-06-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0003_auto_20200608_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepropertiesannotation',
            name='pixelFraction',
            field=models.CharField(max_length=200),
        ),
    ]
