# Generated by Django 3.0.4 on 2020-04-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0003_auto_20200418_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
