# Generated by Django 3.0.4 on 2020-06-14 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0004_auto_20200608_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=2000)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'HelpTable',
            },
        ),
    ]
