# Generated by Django 3.0.4 on 2020-04-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0004_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
    ]
