# Generated by Django 3.0.4 on 2020-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0005_remove_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utype',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
