# Generated by Django 3.0.4 on 2020-06-15 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0005_helptable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUSTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('details', models.CharField(max_length=2000)),
                ('country', models.CharField(max_length=2000)),
                ('createdon', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedon', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ContactUSTable',
            },
        ),
    ]
