# Generated by Django 3.0.4 on 2020-06-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0006_contactustable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactustable',
            name='attend',
            field=models.BooleanField(default=False),
        ),
    ]
