# Generated by Django 3.0.4 on 2020-04-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrandAnalysisApp', '0006_user_utype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCustom',
        ),
    ]
